version: '3'

services: 
    backend:
        container_name: fs_backend
        restart: on-failure
        build:
            context: .
        depends_on: 
            - postgres
        networks: 
            - fs_network
        env_file: 
            - .env
        volumes: 
            - ./:/file_sharing
        ports:
            - 5000:5000

    postgres:
        container_name: fs_db
        image: postgres:12-alpine
        restart: on-failure
        ports:
            - 5432:5432
        env_file:
            - .env
        networks: 
            - fs_network
        volumes: 
            - fs-postgres-data:/var/lib/postgresql/data

networks: 
    fs_network:
        driver: bridge

volumes:
    fs-postgres-data: